### ISSUE TITLE
demo里面列表到详情最佳实践打开列表页报错				

### ISSUE THREAD

**Issue by dpjs** [dcloudio/mui#318]
mui.min.js:7 Uncaught TypeError: Cannot read property 'addEventListener' of undefined
    at d._initEvent (http://127.0.0.1:8020/sdstisp/common/mui/js/mui.min.js:7:14124)
    at d._init (http://127.0.0.1:8020/sdstisp/common/mui/js/mui.min.js:7:12176)
    at d._init (http://127.0.0.1:8020/sdstisp/common/mui/js/mui.min.js:7:8174)
    at d.f.(anonymous function) [as _init] (http://127.0.0.1:8020/sdstisp/common/mui/js/mui.min.js:7:7186)
    at d.init (http://127.0.0.1:8020/sdstisp/common/mui/js/mui.min.js:7:12014)
    at d.init (http://127.0.0.1:8020/sdstisp/common/mui/js/mui.min.js:7:7838)
    at d.f.(anonymous function) [as init] (http://127.0.0.1:8020/sdstisp/common/mui/js/mui.min.js:7:7186)
    at new d (http://127.0.0.1:8020/sdstisp/common/mui/js/mui.min.js:7:6960)
    at Array.a.fn.pullRefresh (http://127.0.0.1:8020/sdstisp/common/mui/js/mui.min.js:7:31726)
    at Function.handle (http://127.0.0.1:8020/sdstisp/common/mui/js/mui.min.js:7:1469)

**Comment by webcssphp** [comment]
放到浏览器中打开的是报这个错
TypeError: this.scroller is undefined
hbuilder 边改边看 web 浏览器 是报这个错
[Web浏览器] "Uncaught TypeError: Cannot read property 'addEventListener' of undefined"	/hello-mui/js/mui.min.js (7)

**Comment by nearwmy** [comment]
demo需要在5+runtime 的环境下运行。直接放在web浏览器上运行是不行的，你可以在HBuilder中真机运行，就可以看到效果了
