### ISSUE TITLE
examples/hello-mui/examples/best-practices/list-to-detail/listview.html页面报错

### ISSUE THREAD

**Issue by lxsea20150901** [dcloudio/mui#329]
examples/hello-mui/examples/best-practices/list-to-detail/listview.html页面报错

Uncaught TypeError: Cannot read property 'addEventListener' of undefined
    at d._initEvent (file:///C:/Users/Administrator/Desktop/mui-master/examples/hello-mui/js/mui.min.js:7:14123)
    at d._init (file:///C:/Users/Administrator/Desktop/mui-master/examples/hello-mui/js/mui.min.js:7:12176)
    at d._init (file:///C:/Users/Administrator/Desktop/mui-master/examples/hello-mui/js/mui.min.js:7:8174)
    at d.f.(anonymous function) [as _init] (file:///C:/Users/Administrator/Desktop/mui-master/examples/hello-mui/js/mui.min.js:7:7186)
    at d.init (file:///C:/Users/Administrator/Desktop/mui-master/examples/hello-mui/js/mui.min.js:7:12014)
    at d.init (file:///C:/Users/Administrator/Desktop/mui-master/examples/hello-mui/js/mui.min.js:7:7838)
    at d.f.(anonymous function) [as init] (file:///C:/Users/Administrator/Desktop/mui-master/examples/hello-mui/js/mui.min.js:7:7186)
    at new d (file:///C:/Users/Administrator/Desktop/mui-master/examples/hello-mui/js/mui.min.js:7:6960)
    at Array.a.fn.pullRefresh (file:///C:/Users/Administrator/Desktop/mui-master/examples/hello-mui/js/mui.min.js:7:31726)
    at Function.handle (file:///C:/Users/Administrator/Desktop/mui-master/examples/hello-mui/js/mui.min.js:7:1469)
![Uploading QQ截图20170707194803.png…]()

**Comment by nearwmy** [comment]
此示例需要在plus环境下运行，也就是需要真机运行查看效果，你这应该是直接在浏览器里打开的吧
