### ISSUE TITLE
/mui/examples/hello-mui/examples/best-practices/list-to-detail/listview.html 报错

### ISSUE THREAD

**Issue by hcxxiaomo** [dcloudio/mui#346]
/mui/examples/hello-mui/examples/best-practices/list-to-detail/listview.html直接访问会报错
**mui.min.js:7 Uncaught TypeError: Cannot read property 'addEventListener' of undefined**
    at d._initEvent (file:///Users/Stefan/Documents/git/mui/examples/hello-mui/js/mui.min.js:7:14124)
    at d._init (file:///Users/Stefan/Documents/git/mui/examples/hello-mui/js/mui.min.js:7:12176)
    at d._init (file:///Users/Stefan/Documents/git/mui/examples/hello-mui/js/mui.min.js:7:8174)
    at d.f.(anonymous function) [as _init] (file:///Users/Stefan/Documents/git/mui/examples/hello-mui/js/mui.min.js:7:7186)
    at d.init (file:///Users/Stefan/Documents/git/mui/examples/hello-mui/js/mui.min.js:7:12014)
    at d.init (file:///Users/Stefan/Documents/git/mui/examples/hello-mui/js/mui.min.js:7:7838)
    at d.f.(anonymous function) [as init] (file:///Users/Stefan/Documents/git/mui/examples/hello-mui/js/mui.min.js:7:7186)
    at new d (file:///Users/Stefan/Documents/git/mui/examples/hello-mui/js/mui.min.js:7:6960)
    at Array.a.fn.pullRefresh (file:///Users/Stefan/Documents/git/mui/examples/hello-mui/js/mui.min.js:7:31726)
    at Function.handle (file:///Users/Stefan/Documents/git/mui/examples/hello-mui/js/mui.min.js:7:1469)

**Comment by hcxxiaomo** [comment]
已经测试了，在手机端是正确的，在浏览器端访问会有错误。
这个问题已经完结 。

**Comment by hbcui1984** [comment]
列表到详情最佳实践只能在App中运行，不支持浏览器环境下运行
